spring:
  datasource:
    continue-on-error: true
    #sepcific URL for Docker usage, otherwise use localhost
    url: jdbc:postgresql://172.16.180.38:5432/Spring_Boot
    password: postgres
    username: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
camunda.bpm.admin-user:
  id: demo
  password: demo
